### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by kN6jq** [witmy/my-springsecurity-plus#6]
报错内容大概如下

```
Caused by: java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [mybatis-mappers/]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access. at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1385) ~[tomcat-embed-core-9.0.36.jar:9.0.36] at org.apache.catalina.loader.WebappClassLoaderBase.getResource(WebappClassLoaderBase.java:1038) ~[tomcat-embed-core-9.0.36.jar:9.0.36]
```

解决办法

修改mybaits配置

```
#mybatis配置
mybatis:
  type-aliases-package: com.codermy.myspringsecurityplus.entity
#  mapper-locations: classpath:/mybatis-mappers/*
  mapper-locations: classpath*:mybatis-mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
```

![image](https://github.com/user-attachments/assets/8b568a36-03c4-4f7e-945e-bcef45c0b151)
